### ISSUE TITLE
API structure

### ISSUE THREAD

**Issue by mapsam** [mapbox/vtquery#1]
Current options:

### 🍎 Single buffer query

```javascript
const vtquery = require('vtquery');
vtquery(vector_tile_buffer, lng, lat, function(err, results) {
  // results
});
```

### 🍌 Multiple buffers in query

```javascript
const vtquery = require('vtquery');
const bufferArray = [buffer1, buffer2, buffer3];
vtquery(bufferArray, lng, lat, function(err, results) {
  // results
});
```

### 🍊 options

```javascript
const vtquery = require('vtquery');
const bufferArray = [buffer1, buffer2, buffer3];
const options = {
  longitude: 20.2,
  latitude: 47.3,
  radius: 10 // which unit? 
};
vtquery(bufferArray, options, function(err, results) {
  // results
});
```

### 🍇 options with bufferArray included

```javascript
const vtquery = require('vtquery');
const options = {
  longitude: 20.2,
  latitude: 47.3,
  radius: 10, // which unit? 
  tiles: [
    { buffer: new Buffer(1), z: 1, x: 1, y: 1 },
    { buffer: new Buffer(2), z: 1, x: 0, y: 1 }
  ]
};
vtquery(options, function(err, results) {
  // results
});
```

Since we'll be required to turn tile coordinates into lng/lat, we'll need to know zxy values for each buffer, which means we are forced into option 🍇 unless we go with option 🍌 where we only query a single buffer and we'll know the zxy in javascript and can use spherical mercator.

Leaning towards 🍇.

cc @GretaCB @millzpaugh @springmeyer

**Comment by GretaCB** [comment]
@mapsam Love this layout :) Now I'm hungry

Question: Is there any difference between these two?
```javascript
const bufferArray = [buffer1, buffer2, buffer3];
```
...
```javascript
tiles: [
    { buffer: new Buffer(1), z: 1, x: 1, y: 1 },
    { buffer: new Buffer(2), z: 1, x: 0, y: 1 }
  ]
```

**Comment by mapsam** [comment]
@GretaCB nom nom

The first one is an array of raw buffers, while the second is an array of objects that include the raw buffers and zxy info.

**Comment by GretaCB** [comment]
@mapsam Coo, reason I ask is to see what an additional option would look like:

```javascript
const vtquery = require('vtquery');
const tiles = [
    { buffer: new Buffer(1), z: 1, x: 1, y: 1 },
    { buffer: new Buffer(2), z: 1, x: 0, y: 1 }
]
vtquery(tiles, lng, lat, function(err, results) {
  // results
});
```

But realizing this is synonymous with 🍌 . So, also agree having it all in one chunk sounds nice and easy. 

The only reason I can think that 🍇 might not be the way to go is if managing a big options object is any particular hassle from within vtquery. Other than that, from a user perspective, 🍇 looks 👌

**Comment by mapsam** [comment]
Agree with you @GretaCB - the big options object isn't the most ideal/appealing from a node-addon perspective. I'm pretty open to what we do, perhaps a combination like:

```javascript
const tiles = [
    { buffer: new Buffer(1), z: 1, x: 1, y: 1 },
    { buffer: new Buffer(2), z: 1, x: 0, y: 1 }
];
const ll = [lng, lat];
const options = { radius: 10 }; // and other things that aren't required?
vtquery(tiles, ll, options, callback);
```

**Comment by springmeyer** [comment]
> vtquery(tiles, ll, options, callback);

👍  This last one looks great. Nicely encapsulates the two types of required args and optional options. I presume if `radius` is not provided it will default to `0` which enables the pure `point-in-polygon` usecase.

**Comment by mapsam** [comment]
Great! Thanks @GretaCB and @springmeyer. I'll run with `vtquery(tiles, ll, options, callback);`.

**Comment by mapsam** [comment]
Going to call this one 👍  now that #19 has been merged. Thanks for the feedback!
