### ISSUE TITLE
More default compiler warnings

### ISSUE THREAD

**Issue by springmeyer** [mapbox/vtquery#11]
Enabling more compiler warnings for an existing project can be painful. It is better to do it from the start so you can think about how to achieve the cleanest and most warning free code as you design.

In this light I noticed we were missing some common compiler warning flags in this project, because I missed them in node-cpp-skel. So, we should pull over https://github.com/mapbox/node-cpp-skel/pull/78

refs mapbox/cpp#37

**Comment by mapsam** [comment]
Done in 919b99ad465cb4aa06c1f016df0f2f3fdda70338
