### ISSUE TITLE
Revise Readme

### ISSUE THREAD

**Issue by springmeyer** [mapbox/vtquery#16]
This project is moving forward and close to being usable. It's time to revise the readme to orient to an external audience. So I think the `Things to remember` and `Loop architecture proposals` could be moved to tickets, where appropriate, and the develop section could be touched up to change `node-cpp-skel` -> `vtquery`.

/cc @mapsam

**Comment by mapsam** [comment]
Ready in https://github.com/mapbox/vtquery/pull/23 @springmeyer
