### ISSUE TITLE
Fork from node-cpp-skel

### ISSUE THREAD

**Issue by mapsam** [mapbox/vtquery#2]
This will be a node addon - let's use node-cpp-skel to do the heavy lifting. 🏋️‍♀️ 

@GretaCB @springmeyer @millzpaugh

**Comment by springmeyer** [comment]
Conceptually I think this project can be (eventually) both a header-only lib (with C++ unit tests) and a node addon binding it (with further unit tests in JS). In the near term, a simple approach would be to have it be a node addon, but with headers organized in `include/` for code that can/will eventually be header-only libs packaged separately in mason.

**Comment by mapsam** [comment]
node-cpp-skel was incorporated in #7 🎉 

Going to open a separate issue for organizing things for preparation as header-only distribution.
