### ISSUE TITLE
radius unit -> convert to tile coordinates

### ISSUE THREAD

**Issue by mapsam** [mapbox/vtquery#21]
We need to decide what the unit is for radius (currently `meters` in the tilequery endpoint) and how to convert those meters into tile coordinates for using in the closest point algorithm. 

cc @springmeyer @flippmoke @GretaCB

**Comment by springmeyer** [comment]
> We need to decide what the unit is for radius (currently meters in the tilequery endpoint)

👍  for keeping back compat.

> and how to convert those meters into tile coordinates for using in the closest point algorithm.

This will be so great in the future!

**Comment by flippmoke** [comment]
I would suggest using https://github.com/mapbox/cheap-ruler-cpp

**Comment by mapsam** [comment]
Thanks @flippmoke (and @mourner @tmpsantos @brunoabinader 👏) - seems like the approach for vtquery would then be:

1. Get the xy (in tile coordinates) from `closest_point`
1. convert that xy into lng/lat (`LLf`)
1. Using the original query lng/lat (`LLq`), get the distance between `LLq` and `LLf` in meters
1. compare against radius provided by user

Does that seem right?

**Comment by mapsam** [comment]
This is set up in 11573a1bf219b7d938b919dfb651329659a2957a but leaves an open question:

This effectively gets rid of the `closest_point_info.distance` value (since this is in tile coordinates and we need lnglat). Therefore we are using `closest_point_info.x` and `closest_point_info.y` to get the lng/lat values. Is this okay? Or is there a way to do all of this in tile coordinates without having to convert to lnglat for every feature?

**Comment by mapsam** [comment]
Closing for now - cheap-ruler is excellent 🎉
