### ISSUE TITLE
invalid ELF header when installing remote binary

### ISSUE THREAD

**Issue by mapsam** [mapbox/vtquery#47]
Getting the following error when installing vtquery from a remote binary: 

```
Error: /home/travis/...../node_modules/@mapbox/vtquery/lib/binding/vtquery.node: invalid ELF header
```

Quick searching suggests this error comes from using a binary built with on operating system architecture and trying to use it on another. The binary was built with Node 4 on Trusty, and I'm using it in the same.

cc @mapbox/core-tech

**Comment by springmeyer** [comment]
What do you get if you run `file lib/binding/vtquery.node`?

**Comment by mapsam** [comment]
Looks like the binding was included in the `npm publish` since we don't have an .npmignore file. Going to add that to #46 and try again with 0.1.0-dev-3

**Comment by mapsam** [comment]
Resolved in https://github.com/mapbox/vtquery/commit/d26f42c3512c16850671c1cfb618115437d8aa36
