### ISSUE TITLE
Add LICENSE.md

### ISSUE THREAD

**Issue by mapsam** [mapbox/vtquery#5]
> BSD2

@springmeyer @GretaCB @millzpaugh

**Comment by springmeyer** [comment]
👍

**Comment by mapsam** [comment]
Let's add the node-cpp-skel badge as well 💀

**Comment by mapsam** [comment]
ready in #23

**Comment by springmeyer** [comment]
@mapsam I just noticed that #23 added CC0 instead of BSD 2. I presume that was a copy/paste error? (since we intend to use CC0 for skels and BSD 2 for code based on them).

**Comment by mapsam** [comment]
Woops. Will update in a separate PR @springmeyer
