### ISSUE TITLE
decompress tiles using gzip-hpp

### ISSUE THREAD

**Issue by mapsam** [mapbox/vtquery#52]
Let's allow users to pass in gzipped tiles, and auto-detect if they are gzipped. 

cc @GretaCB @springmeyer

**Comment by springmeyer** [comment]
👍  plan move on this once https://github.com/mapbox/gzip-hpp/milestone/1 is finished.

**Comment by springmeyer** [comment]
underway at ~~#73~~ #95

**Comment by springmeyer** [comment]
done in #95
