### ISSUE TITLE
update mason packages to released versions

### ISSUE THREAD

**Issue by mapsam** [mapbox/vtquery#54]
Before 0.1.x is released, let's make sure vtquery is using released versions of libraries. Here's where we are at:

### ✅ geometry.hpp `96d3505`

https://github.com/mapbox/mason/tree/master/scripts/geometry

~~https://github.com/mapbox/vtquery/commit/1e4d11622882629b4fdee61ed1576ba073471dda#diff-a213025e5b87b712fdc0007bd3a0e87b most recent update was part of vtzero/vector-tile updates and moved away from the latest 0.9.2 official release. Working off this commit https://github.com/mapbox/geometry.hpp/commit/96d350510c0e6738a903be40e8138c7305f3e33f from geometry.hpp. Will need some 👀 from @flippmoke @artemp on this one I think.~~

**Update: we'll plan on releasing on a gitsha!**

### vtzero `533b811` 

https://github.com/mapbox/mason/tree/master/scripts/vtzero

https://github.com/mapbox/vtquery/commit/1e4d11622882629b4fdee61ed1576ba073471dda#diff-a213025e5b87b712fdc0007bd3a0e87b commit with most recent update was related to vector-tile 2.x development branch - hoping current master should work just fine.

- [x] release latest commit on mason to test https://github.com/mapbox/vtzero/commit/7adde32a034547ddccde0eb5434adb7c47ed2837 (cc @GretaCB) https://github.com/mapbox/mason/pull/542
- [x] needs first official release tagged
- [x] add release to mason
- [x] updated in vtquery

### ✅  spatial-algorithms `cdda174` 

https://github.com/mapbox/mason/tree/master/scripts/spatial-algorithms

https://github.com/mapbox/vtquery/commit/105f1d61c8c102563cdc14292d7923d8f9d42c7a#diff-a213025e5b87b712fdc0007bd3a0e87b commit with most recent update to the version shows no need to specify number type in closest point info

  - [x] needs first official release tagged https://github.com/mapbox/spatial-algorithms/issues/12
  - [x] add release to mason https://github.com/mapbox/mason/pull/540
  - [x] updated in vtquery https://github.com/mapbox/vtquery/pull/57

### ✅ vector-tile `f4728da`

https://github.com/mapbox/mason/tree/master/scripts/vector-tile

Pending 2.x release. 

- [x] release 2.x (at least an rc) https://github.com/mapbox/mason/pull/557
- [x] tag on mason
- [x] update in vtquery

cc @mapbox/core-tech

**Comment by mapsam** [comment]
Updated most recent updates to these libraries ☝️ and possible next steps. Will need eyes from @flippmoke @artemp @joto @springmeyer about whether we can go out with these dev releases or if we need formal tags on Mason.

**Comment by mapsam** [comment]
Using the most recent version of vtzero, I'm running into the following errors (presumably because vector-tile is out of sync?)

```
/Users/mapsam/mapbox/vtquery/mason_packages/.link/include/mapbox/vector_tile/handlers.hpp:42:5: error: no matching function for call to
      'decode_point_geometry'
    vtzero::decode_point_geometry(f.geometry(), false, detail::point_geometry_handler<CoordinateType>(mp));
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/mapsam/mapbox/vtquery/mason_packages/.link/include/mapbox/vector_tile.hpp:20:24: note: in instantiation of function template specialization
      'mapbox::vector_tile::detail::extract_geometry_point<long long>' requested here
        return detail::extract_geometry_point<CoordinateType>(f);
                       ^
../src/vtquery.cpp:363:111: note: in instantiation of function template specialization 'mapbox::vector_tile::extract_geometry<long long>' requested here
                        auto const cp_info = mapbox::geometry::algorithms::closest_point(mapbox::vector_tile::extract_geometry<int64_t>(feature), que...
                                                                                                              ^
/Users/mapsam/mapbox/vtquery/mason_packages/.link/include/vtzero/geometry.hpp:369:53: note: candidate function template not viable: requires 2 arguments, but
      3 were provided
    typename detail::get_result<TGeomHandler>::type decode_point_geometry(const geometry& geometry, TGeomHandler&& geom_handler) {
```

cc @flippmoke maybe I need a vector-tile 2.x update?

**Comment by flippmoke** [comment]
@mapsam yes, I think we need a vector-tile 2.x update here.

**Comment by mapsam** [comment]
@flippmoke the update worked great 👍  https://github.com/mapbox/mason/pull/557

**Comment by mapsam** [comment]
I suspect we'll go live with a dev version of lib vector-tile as well `f4728da`, and perhaps a pre-1.x vtzero depending on the release timeline there. So the last thing here is vtzero!

**Comment by mapsam** [comment]
Updating Mason to a released version https://github.com/mapbox/vtquery/pull/62

**Comment by mapsam** [comment]
Going to release 0.1.0 with a dev version of vtzero!
