### ISSUE TITLE
Why zxy values extracted as int64_t and then casted to uint32_t ?

### ISSUE THREAD

**Issue by artemp** [mapbox/vtquery#87]
https://github.com/mapbox/vtquery/blob/80d6515cdf7267745ba8199493b5dd0fc0a0426a/src/vtquery.cpp#L505-L514

Looks untidy ^. Why not using `int32Value()` and store z,x,y as signed int ?
/cc @mapsam

**Comment by mapsam** [comment]
Good question @artemp - I don't recall why we used int64 originally. I'll work on a PR to update and avoid needing to cast the values.

**Comment by springmeyer** [comment]
I think this was partially addressed in #88, but there is more to discuss in a final review - let's do that at #98
